{% set name = "icub-models" %}
{% set version = "3.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/icub-models/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd54930764000148f63e28f611e11eb47a202c81ca43c963771c6bbf692c3b53

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - multisheller

  host:
    - python
  run:
    - python
  run_constrained:
    # https://github.com/robotology/icub-models/releases/tag/v2.8.0
    - libgazebo-yarp-plugins >=4.12.0

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
    - pip
  files:
    - test
  commands:
    - test -f ${PREFIX}/include/iCubModels/iCubModels.h  # [not win]
    - test -f ${PREFIX}/lib/libicub-models.so  # [linux]
    - test -f ${PREFIX}/lib/libicub-models.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/icub-models/icub-modelsConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\iCubModels\\iCubModels.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\icub-models.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\icub-models.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\CMake\\icub-modelsConfig.cmake exit 1  # [win]
    - test $(pip list | grep icub-models | tr -s " " | grep $PKG_VERSION | wc -l) -eq 1  # [unix]
    - pip check
  imports:
    - icub_models

about:
  home: https://github.com/robotology/icub-models
  license: CC-BY-SA-4.0
  license_file: LICENSE
  summary: Official URDF and SDF models of the iCub humanoid robot.

extra:
  recipe-maintainers:
    - traversaro
